import { LapData } from "f1-2021-udp/build/src/parsers/2_LapData/types"
import { ParticipantData } from "f1-2021-udp/build/src/parsers/4_Participants/types"

export const lap: LapData[] = [
    {
        "m_lastLapTimeInMS": 129854,
        "m_currentLapTimeInMS": 120869,
        "m_sector1TimeInMS": 31300,
        "m_sector2TimeInMS": 3992,
        "m_lapDistance": 6644.05322265625,
        "m_totalDistance": 13647.638671875,
        "m_safetyCarDelta": 0,
        "m_carPosition": 19,
        "m_currentLapNum": 2,
        "m_pitStatus": 0,
        "m_numPitStops": 0,
        "m_sector": 2,
        "m_currentLapInvalid": 0,
        "m_penalties": 2,
        "m_warnings": 0,
        "m_numUnservedDriveThroughPens": 0,
        "m_numUnservedStopGoPens": 0,
        "m_gridPosition": 6,
        "m_driverStatus": 4,
        "m_resultStatus": 2,
        "m_pitLaneTimerActive": 0,
        "m_pitLaneTimeInLaneInMS": 0,
        "m_pitStopTimerInMS": 0,
        "m_pitStopShouldServePen": 0
    },
    {
        "m_lastLapTimeInMS": 105676,
        "m_currentLapTimeInMS": 21085,
        "m_sector1TimeInMS": 0,
        "m_sector2TimeInMS": 0,
        "m_lapDistance": 2033.287109375,
        "m_totalDistance": 16040.4580078125,
        "m_safetyCarDelta": 0,
        "m_carPosition": 9,
        "m_currentLapNum": 3,
        "m_pitStatus": 0,
        "m_numPitStops": 0,
        "m_sector": 0,
        "m_currentLapInvalid": 0,
        "m_penalties": 0,
        "m_warnings": 0,
        "m_numUnservedDriveThroughPens": 0,
        "m_numUnservedStopGoPens": 0,
        "m_gridPosition": 10,
        "m_driverStatus": 4,
        "m_resultStatus": 2,
        "m_pitLaneTimerActive": 0,
        "m_pitLaneTimeInLaneInMS": 0,
        "m_pitStopTimerInMS": 0,
        "m_pitStopShouldServePen": 0
    },
    {
        "m_lastLapTimeInMS": 111017,
        "m_currentLapTimeInMS": 21085,
        "m_sector1TimeInMS": 0,
        "m_sector2TimeInMS": 0,
        "m_lapDistance": 1573.6904296875,
        "m_totalDistance": 15580.861328125,
        "m_safetyCarDelta": 0,
        "m_carPosition": 12,
        "m_currentLapNum": 3,
        "m_pitStatus": 0,
        "m_numPitStops": 0,
        "m_sector": 0,
        "m_currentLapInvalid": 0,
        "m_penalties": 0,
        "m_warnings": 0,
        "m_numUnservedDriveThroughPens": 0,
        "m_numUnservedStopGoPens": 0,
        "m_gridPosition": 9,
        "m_driverStatus": 4,
        "m_resultStatus": 2,
        "m_pitLaneTimerActive": 0,
        "m_pitLaneTimeInLaneInMS": 0,
        "m_pitStopTimerInMS": 0,
        "m_pitStopShouldServePen": 0
    },
    {
        "m_lastLapTimeInMS": 143624,
        "m_currentLapTimeInMS": 106006,
        "m_sector1TimeInMS": 32266,
        "m_sector2TimeInMS": 50296,
        "m_lapDistance": 6772.59619140625,
        "m_totalDistance": 13776.181640625,
        "m_safetyCarDelta": 0,
        "m_carPosition": 18,
        "m_currentLapNum": 2,
        "m_pitStatus": 0,
        "m_numPitStops": 0,
        "m_sector": 2,
        "m_currentLapInvalid": 0,
        "m_penalties": 0,
        "m_warnings": 0,
        "m_numUnservedDriveThroughPens": 0,
        "m_numUnservedStopGoPens": 0,
        "m_gridPosition": 18,
        "m_driverStatus": 4,
        "m_resultStatus": 2,
        "m_pitLaneTimerActive": 0,
        "m_pitLaneTimeInLaneInMS": 0,
        "m_pitStopTimerInMS": 0,
        "m_pitStopShouldServePen": 0
    },
    {
        "m_lastLapTimeInMS": 106520,
        "m_currentLapTimeInMS": 31537,
        "m_sector1TimeInMS": 30990,
        "m_sector2TimeInMS": 0,
        "m_lapDistance": 2295.6220703125,
        "m_totalDistance": 16302.79296875,
        "m_safetyCarDelta": 0,
        "m_carPosition": 4,
        "m_currentLapNum": 3,
        "m_pitStatus": 0,
        "m_numPitStops": 0,
        "m_sector": 1,
        "m_currentLapInvalid": 0,
        "m_penalties": 0,
        "m_warnings": 0,
        "m_numUnservedDriveThroughPens": 0,
        "m_numUnservedStopGoPens": 0,
        "m_gridPosition": 12,
        "m_driverStatus": 4,
        "m_resultStatus": 2,
        "m_pitLaneTimerActive": 0,
        "m_pitLaneTimeInLaneInMS": 0,
        "m_pitStopTimerInMS": 0,
        "m_pitStopShouldServePen": 0
    },
    {
        "m_lastLapTimeInMS": 118034,
        "m_currentLapTimeInMS": 13032,
        "m_sector1TimeInMS": 0,
        "m_sector2TimeInMS": 0,
        "m_lapDistance": 734.6162109375,
        "m_totalDistance": 14741.787109375,
        "m_safetyCarDelta": 0,
        "m_carPosition": 16,
        "m_currentLapNum": 3,
        "m_pitStatus": 0,
        "m_numPitStops": 0,
        "m_sector": 0,
        "m_currentLapInvalid": 0,
        "m_penalties": 0,
        "m_warnings": 0,
        "m_numUnservedDriveThroughPens": 0,
        "m_numUnservedStopGoPens": 0,
        "m_gridPosition": 13,
        "m_driverStatus": 4,
        "m_resultStatus": 2,
        "m_pitLaneTimerActive": 0,
        "m_pitLaneTimeInLaneInMS": 0,
        "m_pitStopTimerInMS": 0,
        "m_pitStopShouldServePen": 0
    },
    {
        "m_lastLapTimeInMS": 118006,
        "m_currentLapTimeInMS": 18638,
        "m_sector1TimeInMS": 0,
        "m_sector2TimeInMS": 0,
        "m_lapDistance": 1157.9345703125,
        "m_totalDistance": 15165.10546875,
        "m_safetyCarDelta": 0,
        "m_carPosition": 14,
        "m_currentLapNum": 3,
        "m_pitStatus": 0,
        "m_numPitStops": 0,
        "m_sector": 0,
        "m_currentLapInvalid": 0,
        "m_penalties": 0,
        "m_warnings": 0,
        "m_numUnservedDriveThroughPens": 0,
        "m_numUnservedStopGoPens": 0,
        "m_gridPosition": 5,
        "m_driverStatus": 4,
        "m_resultStatus": 2,
        "m_pitLaneTimerActive": 0,
        "m_pitLaneTimeInLaneInMS": 0,
        "m_pitStopTimerInMS": 0,
        "m_pitStopShouldServePen": 0
    },
    {
        "m_lastLapTimeInMS": 105492,
        "m_currentLapTimeInMS": 33935,
        "m_sector1TimeInMS": 30747,
        "m_sector2TimeInMS": 0,
        "m_lapDistance": 2455.5478515625,
        "m_totalDistance": 16462.71875,
        "m_safetyCarDelta": 0,
        "m_carPosition": 2,
        "m_currentLapNum": 3,
        "m_pitStatus": 0,
        "m_numPitStops": 0,
        "m_sector": 1,
        "m_currentLapInvalid": 0,
        "m_penalties": 0,
        "m_warnings": 0,
        "m_numUnservedDriveThroughPens": 0,
        "m_numUnservedStopGoPens": 0,
        "m_gridPosition": 11,
        "m_driverStatus": 4,
        "m_resultStatus": 2,
        "m_pitLaneTimerActive": 0,
        "m_pitLaneTimeInLaneInMS": 0,
        "m_pitStopTimerInMS": 0,
        "m_pitStopShouldServePen": 0
    },
    {
        "m_lastLapTimeInMS": 107286,
        "m_currentLapTimeInMS": 21085,
        "m_sector1TimeInMS": 0,
        "m_sector2TimeInMS": 0,
        "m_lapDistance": 1699.0048828125,
        "m_totalDistance": 15706.17578125,
        "m_safetyCarDelta": 0,
        "m_carPosition": 10,
        "m_currentLapNum": 3,
        "m_pitStatus": 0,
        "m_numPitStops": 0,
        "m_sector": 0,
        "m_currentLapInvalid": 0,
        "m_penalties": 0,
        "m_warnings": 0,
        "m_numUnservedDriveThroughPens": 0,
        "m_numUnservedStopGoPens": 0,
        "m_gridPosition": 8,
        "m_driverStatus": 4,
        "m_resultStatus": 2,
        "m_pitLaneTimerActive": 0,
        "m_pitLaneTimeInLaneInMS": 0,
        "m_pitStopTimerInMS": 0,
        "m_pitStopShouldServePen": 0
    },
    {
        "m_lastLapTimeInMS": 107801,
        "m_currentLapTimeInMS": 21085,
        "m_sector1TimeInMS": 0,
        "m_sector2TimeInMS": 0,
        "m_lapDistance": 1581.2822265625,
        "m_totalDistance": 15588.453125,
        "m_safetyCarDelta": 0,
        "m_carPosition": 11,
        "m_currentLapNum": 3,
        "m_pitStatus": 0,
        "m_numPitStops": 0,
        "m_sector": 0,
        "m_currentLapInvalid": 0,
        "m_penalties": 2,
        "m_warnings": 0,
        "m_numUnservedDriveThroughPens": 0,
        "m_numUnservedStopGoPens": 0,
        "m_gridPosition": 3,
        "m_driverStatus": 4,
        "m_resultStatus": 2,
        "m_pitLaneTimerActive": 0,
        "m_pitLaneTimeInLaneInMS": 0,
        "m_pitStopTimerInMS": 0,
        "m_pitStopShouldServePen": 0
    },
    {
        "m_lastLapTimeInMS": 107312,
        "m_currentLapTimeInMS": 21085,
        "m_sector1TimeInMS": 0,
        "m_sector2TimeInMS": 0,
        "m_lapDistance": 2110.0576171875,
        "m_totalDistance": 16117.228515625,
        "m_safetyCarDelta": 0,
        "m_carPosition": 6,
        "m_currentLapNum": 3,
        "m_pitStatus": 0,
        "m_numPitStops": 0,
        "m_sector": 0,
        "m_currentLapInvalid": 0,
        "m_penalties": 2,
        "m_warnings": 0,
        "m_numUnservedDriveThroughPens": 0,
        "m_numUnservedStopGoPens": 0,
        "m_gridPosition": 19,
        "m_driverStatus": 4,
        "m_resultStatus": 2,
        "m_pitLaneTimerActive": 0,
        "m_pitLaneTimeInLaneInMS": 0,
        "m_pitStopTimerInMS": 0,
        "m_pitStopShouldServePen": 0
    },
    {
        "m_lastLapTimeInMS": 116828,
        "m_currentLapTimeInMS": 132801,
        "m_sector1TimeInMS": 30858,
        "m_sector2TimeInMS": 7585,
        "m_lapDistance": 6942.95166015625,
        "m_totalDistance": 13946.537109375,
        "m_safetyCarDelta": 0,
        "m_carPosition": 17,
        "m_currentLapNum": 2,
        "m_pitStatus": 0,
        "m_numPitStops": 0,
        "m_sector": 2,
        "m_currentLapInvalid": 0,
        "m_penalties": 2,
        "m_warnings": 0,
        "m_numUnservedDriveThroughPens": 0,
        "m_numUnservedStopGoPens": 0,
        "m_gridPosition": 16,
        "m_driverStatus": 4,
        "m_resultStatus": 2,
        "m_pitLaneTimerActive": 0,
        "m_pitLaneTimeInLaneInMS": 0,
        "m_pitStopTimerInMS": 0,
        "m_pitStopShouldServePen": 0
    },
    {
        "m_lastLapTimeInMS": 107840,
        "m_currentLapTimeInMS": 33319,
        "m_sector1TimeInMS": 31841,
        "m_sector2TimeInMS": 0,
        "m_lapDistance": 2361.978515625,
        "m_totalDistance": 16369.1494140625,
        "m_safetyCarDelta": 0,
        "m_carPosition": 3,
        "m_currentLapNum": 3,
        "m_pitStatus": 0,
        "m_numPitStops": 0,
        "m_sector": 1,
        "m_currentLapInvalid": 0,
        "m_penalties": 2,
        "m_warnings": 0,
        "m_numUnservedDriveThroughPens": 0,
        "m_numUnservedStopGoPens": 0,
        "m_gridPosition": 2,
        "m_driverStatus": 4,
        "m_resultStatus": 2,
        "m_pitLaneTimerActive": 0,
        "m_pitLaneTimeInLaneInMS": 0,
        "m_pitStopTimerInMS": 0,
        "m_pitStopShouldServePen": 0
    },
    {
        "m_lastLapTimeInMS": 107730,
        "m_currentLapTimeInMS": 21085,
        "m_sector1TimeInMS": 0,
        "m_sector2TimeInMS": 0,
        "m_lapDistance": 2085.2294921875,
        "m_totalDistance": 16092.400390625,
        "m_safetyCarDelta": 0,
        "m_carPosition": 7,
        "m_currentLapNum": 3,
        "m_pitStatus": 0,
        "m_numPitStops": 0,
        "m_sector": 0,
        "m_currentLapInvalid": 0,
        "m_penalties": 4,
        "m_warnings": 0,
        "m_numUnservedDriveThroughPens": 0,
        "m_numUnservedStopGoPens": 0,
        "m_gridPosition": 15,
        "m_driverStatus": 4,
        "m_resultStatus": 2,
        "m_pitLaneTimerActive": 0,
        "m_pitLaneTimeInLaneInMS": 0,
        "m_pitStopTimerInMS": 0,
        "m_pitStopShouldServePen": 0
    },
    {
        "m_lastLapTimeInMS": 107894,
        "m_currentLapTimeInMS": 16227,
        "m_sector1TimeInMS": 0,
        "m_sector2TimeInMS": 0,
        "m_lapDistance": 978.6611328125,
        "m_totalDistance": 14985.83203125,
        "m_safetyCarDelta": 0,
        "m_carPosition": 15,
        "m_currentLapNum": 3,
        "m_pitStatus": 0,
        "m_numPitStops": 0,
        "m_sector": 0,
        "m_currentLapInvalid": 0,
        "m_penalties": 6,
        "m_warnings": 0,
        "m_numUnservedDriveThroughPens": 0,
        "m_numUnservedStopGoPens": 0,
        "m_gridPosition": 14,
        "m_driverStatus": 4,
        "m_resultStatus": 2,
        "m_pitLaneTimerActive": 0,
        "m_pitLaneTimeInLaneInMS": 0,
        "m_pitStopTimerInMS": 0,
        "m_pitStopShouldServePen": 0
    },
    {
        "m_lastLapTimeInMS": 115965,
        "m_currentLapTimeInMS": 20763,
        "m_sector1TimeInMS": 0,
        "m_sector2TimeInMS": 0,
        "m_lapDistance": 1336.3369140625,
        "m_totalDistance": 15343.5078125,
        "m_safetyCarDelta": 0,
        "m_carPosition": 13,
        "m_currentLapNum": 3,
        "m_pitStatus": 0,
        "m_numPitStops": 0,
        "m_sector": 0,
        "m_currentLapInvalid": 0,
        "m_penalties": 2,
        "m_warnings": 0,
        "m_numUnservedDriveThroughPens": 0,
        "m_numUnservedStopGoPens": 0,
        "m_gridPosition": 17,
        "m_driverStatus": 4,
        "m_resultStatus": 2,
        "m_pitLaneTimerActive": 0,
        "m_pitLaneTimeInLaneInMS": 0,
        "m_pitStopTimerInMS": 0,
        "m_pitStopShouldServePen": 0
    },
    {
        "m_lastLapTimeInMS": 108053,
        "m_currentLapTimeInMS": 31792,
        "m_sector1TimeInMS": 31501,
        "m_sector2TimeInMS": 0,
        "m_lapDistance": 2274.0908203125,
        "m_totalDistance": 16281.26171875,
        "m_safetyCarDelta": 0,
        "m_carPosition": 5,
        "m_currentLapNum": 3,
        "m_pitStatus": 0,
        "m_numPitStops": 0,
        "m_sector": 1,
        "m_currentLapInvalid": 0,
        "m_penalties": 4,
        "m_warnings": 0,
        "m_numUnservedDriveThroughPens": 0,
        "m_numUnservedStopGoPens": 0,
        "m_gridPosition": 4,
        "m_driverStatus": 4,
        "m_resultStatus": 2,
        "m_pitLaneTimerActive": 0,
        "m_pitLaneTimeInLaneInMS": 0,
        "m_pitStopTimerInMS": 0,
        "m_pitStopShouldServePen": 0
    },
    {
        "m_lastLapTimeInMS": 107188,
        "m_currentLapTimeInMS": 21085,
        "m_sector1TimeInMS": 0,
        "m_sector2TimeInMS": 0,
        "m_lapDistance": 2083.767578125,
        "m_totalDistance": 16090.9384765625,
        "m_safetyCarDelta": 0,
        "m_carPosition": 8,
        "m_currentLapNum": 3,
        "m_pitStatus": 0,
        "m_numPitStops": 0,
        "m_sector": 0,
        "m_currentLapInvalid": 0,
        "m_penalties": 0,
        "m_warnings": 0,
        "m_numUnservedDriveThroughPens": 0,
        "m_numUnservedStopGoPens": 0,
        "m_gridPosition": 20,
        "m_driverStatus": 4,
        "m_resultStatus": 2,
        "m_pitLaneTimerActive": 0,
        "m_pitLaneTimeInLaneInMS": 0,
        "m_pitStopTimerInMS": 0,
        "m_pitStopShouldServePen": 0
    },
    {
        "m_lastLapTimeInMS": 0,
        "m_currentLapTimeInMS": 182632,
        "m_sector1TimeInMS": 7860,
        "m_sector2TimeInMS": 0,
        "m_lapDistance": 159.8017578125,
        "m_totalDistance": 159.8017578125,
        "m_safetyCarDelta": 0,
        "m_carPosition": 20,
        "m_currentLapNum": 1,
        "m_pitStatus": 1,
        "m_numPitStops": 0,
        "m_sector": 0,
        "m_currentLapInvalid": 0,
        "m_penalties": 0,
        "m_warnings": 0,
        "m_numUnservedDriveThroughPens": 0,
        "m_numUnservedStopGoPens": 0,
        "m_gridPosition": 7,
        "m_driverStatus": 0,
        "m_resultStatus": 7,
        "m_pitLaneTimerActive": 1,
        "m_pitLaneTimeInLaneInMS": 0,
        "m_pitStopTimerInMS": 0,
        "m_pitStopShouldServePen": 0
    },
    {
        "m_lastLapTimeInMS": 106018,
        "m_currentLapTimeInMS": 36980,
        "m_sector1TimeInMS": 31177,
        "m_sector2TimeInMS": 0,
        "m_lapDistance": 2585.1826171875,
        "m_totalDistance": 16592.353515625,
        "m_safetyCarDelta": 0,
        "m_carPosition": 1,
        "m_currentLapNum": 3,
        "m_pitStatus": 0,
        "m_numPitStops": 0,
        "m_sector": 1,
        "m_currentLapInvalid": 0,
        "m_penalties": 0,
        "m_warnings": 0,
        "m_numUnservedDriveThroughPens": 0,
        "m_numUnservedStopGoPens": 0,
        "m_gridPosition": 1,
        "m_driverStatus": 4,
        "m_resultStatus": 2,
        "m_pitLaneTimerActive": 0,
        "m_pitLaneTimeInLaneInMS": 0,
        "m_pitStopTimerInMS": 0,
        "m_pitStopShouldServePen": 0
    },
    {
        "m_lastLapTimeInMS": 0,
        "m_currentLapTimeInMS": 0,
        "m_sector1TimeInMS": 0,
        "m_sector2TimeInMS": 0,
        "m_lapDistance": 0,
        "m_totalDistance": 0,
        "m_safetyCarDelta": 0,
        "m_carPosition": 0,
        "m_currentLapNum": 0,
        "m_pitStatus": 0,
        "m_numPitStops": 0,
        "m_sector": 0,
        "m_currentLapInvalid": 0,
        "m_penalties": 0,
        "m_warnings": 0,
        "m_numUnservedDriveThroughPens": 0,
        "m_numUnservedStopGoPens": 0,
        "m_gridPosition": 0,
        "m_driverStatus": 0,
        "m_resultStatus": 0,
        "m_pitLaneTimerActive": 0,
        "m_pitLaneTimeInLaneInMS": 0,
        "m_pitStopTimerInMS": 0,
        "m_pitStopShouldServePen": 0
    },
    {
        "m_lastLapTimeInMS": 0,
        "m_currentLapTimeInMS": 0,
        "m_sector1TimeInMS": 0,
        "m_sector2TimeInMS": 0,
        "m_lapDistance": 0,
        "m_totalDistance": 0,
        "m_safetyCarDelta": 0,
        "m_carPosition": 0,
        "m_currentLapNum": 0,
        "m_pitStatus": 0,
        "m_numPitStops": 0,
        "m_sector": 0,
        "m_currentLapInvalid": 0,
        "m_penalties": 0,
        "m_warnings": 0,
        "m_numUnservedDriveThroughPens": 0,
        "m_numUnservedStopGoPens": 0,
        "m_gridPosition": 0,
        "m_driverStatus": 0,
        "m_resultStatus": 0,
        "m_pitLaneTimerActive": 0,
        "m_pitLaneTimeInLaneInMS": 0,
        "m_pitStopTimerInMS": 0,
        "m_pitStopShouldServePen": 0
    }
].sort((a, b) => a.m_carPosition - b.m_carPosition)

export const participants: ParticipantData[] = [
    {
        "m_aiControlled": 0,
        "m_driverId": 255,
        "m_networkId": 0,
        "m_teamId": 1,
        "m_myTeam": 0,
        "m_raceNumber": 69,
        "m_nationality": 29,
        "m_name": "Gracz",
        "m_yourTelemetry": 0
    },
    {
        "m_aiControlled": 0,
        "m_driverId": 255,
        "m_networkId": 1,
        "m_teamId": 1,
        "m_myTeam": 0,
        "m_raceNumber": 13,
        "m_nationality": 29,
        "m_name": "Gracz",
        "m_yourTelemetry": 0
    },
    {
        "m_aiControlled": 0,
        "m_driverId": 255,
        "m_networkId": 4,
        "m_teamId": 0,
        "m_myTeam": 0,
        "m_raceNumber": 15,
        "m_nationality": 64,
        "m_name": "Gracz",
        "m_yourTelemetry": 0
    },
    {
        "m_aiControlled": 1,
        "m_driverId": 255,
        "m_networkId": 9,
        "m_teamId": 0,
        "m_myTeam": 0,
        "m_raceNumber": 2,
        "m_nationality": 0,
        "m_name": "Gracz",
        "m_yourTelemetry": 0
    },
    {
        "m_aiControlled": 0,
        "m_driverId": 255,
        "m_networkId": 21,
        "m_teamId": 4,
        "m_myTeam": 0,
        "m_raceNumber": 21,
        "m_nationality": 79,
        "m_name": "Gracz",
        "m_yourTelemetry": 0
    },
    {
        "m_aiControlled": 0,
        "m_driverId": 255,
        "m_networkId": 26,
        "m_teamId": 6,
        "m_myTeam": 0,
        "m_raceNumber": 69,
        "m_nationality": 29,
        "m_name": "Gracz",
        "m_yourTelemetry": 0
    },
    {
        "m_aiControlled": 0,
        "m_driverId": 255,
        "m_networkId": 37,
        "m_teamId": 9,
        "m_myTeam": 0,
        "m_raceNumber": 88,
        "m_nationality": 15,
        "m_name": "Gracz",
        "m_yourTelemetry": 0
    },
    {
        "m_aiControlled": 0,
        "m_driverId": 255,
        "m_networkId": 40,
        "m_teamId": 2,
        "m_myTeam": 0,
        "m_raceNumber": 13,
        "m_nationality": 81,
        "m_name": "Gracz",
        "m_yourTelemetry": 0
    },
    {
        "m_aiControlled": 0,
        "m_driverId": 255,
        "m_networkId": 39,
        "m_teamId": 5,
        "m_myTeam": 0,
        "m_raceNumber": 21,
        "m_nationality": 31,
        "m_name": "Gracz",
        "m_yourTelemetry": 0
    },
    {
        "m_aiControlled": 0,
        "m_driverId": 255,
        "m_networkId": 35,
        "m_teamId": 5,
        "m_myTeam": 0,
        "m_raceNumber": 35,
        "m_nationality": 29,
        "m_name": "Gracz",
        "m_yourTelemetry": 0
    },
    {
        "m_aiControlled": 0,
        "m_driverId": 255,
        "m_networkId": 29,
        "m_teamId": 3,
        "m_myTeam": 0,
        "m_raceNumber": 2,
        "m_nationality": 0,
        "m_name": "Gracz",
        "m_yourTelemetry": 0
    },
    {
        "m_aiControlled": 1,
        "m_driverId": 255,
        "m_networkId": 42,
        "m_teamId": 9,
        "m_myTeam": 0,
        "m_raceNumber": 8,
        "m_nationality": 20,
        "m_name": "Gracz",
        "m_yourTelemetry": 0
    },
    {
        "m_aiControlled": 0,
        "m_driverId": 255,
        "m_networkId": 51,
        "m_teamId": 7,
        "m_myTeam": 0,
        "m_raceNumber": 93,
        "m_nationality": 1,
        "m_name": "Gracz",
        "m_yourTelemetry": 0
    },
    {
        "m_aiControlled": 0,
        "m_driverId": 255,
        "m_networkId": 41,
        "m_teamId": 2,
        "m_myTeam": 0,
        "m_raceNumber": 13,
        "m_nationality": 4,
        "m_name": "Gracz",
        "m_yourTelemetry": 0
    },
    {
        "m_aiControlled": 0,
        "m_driverId": 255,
        "m_networkId": 47,
        "m_teamId": 8,
        "m_myTeam": 0,
        "m_raceNumber": 2,
        "m_nationality": 0,
        "m_name": "Gracz",
        "m_yourTelemetry": 0
    },
    {
        "m_aiControlled": 0,
        "m_driverId": 255,
        "m_networkId": 43,
        "m_teamId": 8,
        "m_myTeam": 0,
        "m_raceNumber": 2,
        "m_nationality": 0,
        "m_name": "Gracz",
        "m_yourTelemetry": 0
    },
    {
        "m_aiControlled": 0,
        "m_driverId": 255,
        "m_networkId": 50,
        "m_teamId": 7,
        "m_myTeam": 0,
        "m_raceNumber": 2,
        "m_nationality": 0,
        "m_name": "Gracz",
        "m_yourTelemetry": 0
    },
    {
        "m_aiControlled": 0,
        "m_driverId": 255,
        "m_networkId": 33,
        "m_teamId": 4,
        "m_myTeam": 0,
        "m_raceNumber": 8,
        "m_nationality": 35,
        "m_name": "Gracz",
        "m_yourTelemetry": 0
    },
    {
        "m_aiControlled": 1,
        "m_driverId": 255,
        "m_networkId": 36,
        "m_teamId": 6,
        "m_myTeam": 0,
        "m_raceNumber": 43,
        "m_nationality": 64,
        "m_name": "Gracz",
        "m_yourTelemetry": 0
    },
    {
        "m_aiControlled": 0,
        "m_driverId": 255,
        "m_networkId": 53,
        "m_teamId": 3,
        "m_myTeam": 0,
        "m_raceNumber": 19,
        "m_nationality": 77,
        "m_name": "Gracz",
        "m_yourTelemetry": 0
    },
    {
        "m_aiControlled": 0,
        "m_driverId": 255,
        "m_networkId": 255,
        "m_teamId": 255,
        "m_myTeam": 0,
        "m_raceNumber": 0,
        "m_nationality": 255,
        "m_name": "",
        "m_yourTelemetry": 0
    },
    {
        "m_aiControlled": 0,
        "m_driverId": 255,
        "m_networkId": 255,
        "m_teamId": 255,
        "m_myTeam": 0,
        "m_raceNumber": 0,
        "m_nationality": 255,
        "m_name": "",
        "m_yourTelemetry": 0
    }
]